## Tensor Operations

In [1]:
import numpy as np
import pandas as pd
from keras.activations import relu

Using TensorFlow backend.


In [7]:
input1 = np.array([[1,2,3,4],
                   [5,6,7,8]])
W = np.array([[-1.4, 0.87, -0.5, 0]]) #weight
b = 1.43

In [8]:
input1.shape, W.shape

((2, 4), (1, 4))

In [9]:
np.dot(W, input1.T)

array([[-1.16, -5.28]])

In [10]:
output = relu(np.dot(W, input1.T) + b)

In [11]:
output

<tf.Tensor: shape=(1, 2), dtype=float64, numpy=array([[0.27, 0.  ]])>

### Element-wise operations

In [12]:
def naive_relu(x):
    assert len(x.shape) == 2
    
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] = max(x[i, j], 0)
    return x

list.copy() hakkında

In [13]:
b = [1,2,3,4]
type(b)

list

In [14]:
a = b
a[0] = 5
b

[5, 2, 3, 4]

In [10]:
b = [1,2,3,4]
c = b.copy()
c[0] = 5
b

[1, 2, 3, 4]

In [15]:
array = np.array([[1,-3,5,-7],
                  [-2,4,-6,8]])

In [16]:
array.shape

(2, 4)

In [17]:
return_value = naive_relu(array)
return_value

array([[1, 0, 5, 0],
       [0, 4, 0, 8]])

In [18]:
def naive_add(x, y):
    assert len(x.shape) == 2
    assert x.shape == y.shape
    
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] += y[i, j]
    return x

In [19]:
x = np.array([[1, 2, 3],
             [3, -14, 5]])
y = np.array([[2, 4, 6],
             [-7, 8, -19]])

In [20]:
return_value = naive_add(x,y)
return_value

array([[  3,   6,   9],
       [ -4,  -6, -14]])

In [21]:
z = x + y
z

array([[  3,   6,   9],
       [ -4,  -6, -14]])

In [22]:
z = np.maximum(z, 0.)
z

array([[3., 6., 9.],
       [0., 0., 0.]])

### Broadcasting

In [23]:
def naive_add_matrix_and_vector(x, y):
    assert len(x.shape) == 2
    assert len(y.shape) == 1
    assert x.shape[1] == y.shape[0]
    
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] += y[j]
    return x

In [24]:
x = np.array([[1,2,3],
              [5,6,7]])

y = np.array([2,5,8])

print(len(x.shape), len(y.shape))

return_value = naive_add_matrix_and_vector(x,y)
return_value

2 1


array([[ 3,  7, 11],
       [ 7, 11, 15]])

In [25]:
z = x + y
z

array([[ 3,  7, 11],
       [ 7, 11, 15]])

In [26]:
x

array([[1, 2, 3],
       [5, 6, 7]])

In [23]:
z

array([[ 3,  7, 11],
       [ 7, 11, 15]])

In [27]:
x = np.random.random((64, 3, 32, 10))
y = np.random.random((32, 10))
z = np.maximum(x, y)
z.shape

(64, 3, 32, 10)

In [28]:
print("ikinci satır",z[1,:])   # ilk kısım satır
print("birinci kolon",z[:,0])   # ikinci kısım kolon

ikinci satır [[[0.45384786 0.91570939 0.84799885 0.56178145 0.93206713 0.81738778
   0.50336494 0.31973168 0.63131045 0.36176074]
  [0.88527232 0.73501036 0.06136211 0.44540921 0.57251685 0.79067569
   0.65736043 0.14462559 0.47277851 0.77008598]
  [0.53879348 0.72824068 0.86015181 0.18213785 0.96693091 0.95756757
   0.99316351 0.81727065 0.88681062 0.94919317]
  [0.93451505 0.69127307 0.77583018 0.47278255 0.96454587 0.37972938
   0.39372324 0.55067566 0.26255381 0.44223451]
  [0.40916657 0.73088804 0.41560452 0.98748364 0.95425833 0.7675575
   0.9108368  0.85366655 0.76447339 0.92825706]
  [0.73072234 0.35700653 0.77882442 0.37017196 0.71425241 0.89801887
   0.92986424 0.53329685 0.96832152 0.93184595]
  [0.24797516 0.66524816 0.99577261 0.60646943 0.5837213  0.5284074
   0.42962253 0.61095352 0.99725867 0.75642455]
  [0.87698501 0.43726703 0.54843697 0.65100973 0.86456805 0.94192676
   0.84729326 0.715747   0.67859    0.65374489]
  [0.62748662 0.76824227 0.79197343 0.94697521 0.8906

### Tensor dot


In [25]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[2, 4], [6, 8], [10, 12]])
x.shape, y.shape

((2, 3), (3, 2))

In [26]:
def naive_matris_dot_matris(x,y):
    assert x.shape[1] == y.shape[0]
    assert y.shape[1] >= 1                #(4,),(,6)
    
    z = x.shape[1]
    x_row = x.shape[0]
    y_column = y.shape[1]
    sum_of_products = 0
    a = np.zeros((x_row, y_column))
    
    for i in range(x_row):
        for j in range(y_column):
            for k in range(z):
                sum_of_products += x[i,k]*y[k,j]  
            a[i,j] = sum_of_products
            sum_of_products = 0
    return a

In [27]:
return_value = naive_matris_dot_matris(x, y)
return_value

array([[ 44.,  56.],
       [ 98., 128.]])

In [29]:
z = np.dot(x, y)
x.shape, y.shape, z.shape, z

((2, 3),
 (3, 2),
 (2, 2),
 array([[ 44,  56],
        [ 98, 128]]))

In [42]:
pd.DataFrame(z)

0    1
0  28   64
1  64  154

In [29]:
x = np.array([[1, 2, 3], [4, 5, 6]])

y = np.array([[2, 4, 6], [8, 10, 12]])

z = np.dot(x, y.T)
z

array([[ 28,  64],
       [ 64, 154]])

In [32]:
pd.DataFrame(y.T)

0   1
0  2   8
1  4  10
2  6  12

In [31]:
pd.DataFrame(y)

0   1   2
0  2   4   6
1  8  10  12

In [33]:
x = np.array([[1, 2, 3], [4, 5, 6]])

y = np.array([[2, 8], [4, 10], [6, 12]])

z = np.dot(x, y)
y.shape, z.shape, z

((3, 2),
 (2, 2),
 array([[ 28,  64],
        [ 64, 154]]))

In [34]:
pd.DataFrame(z)

0    1
0  28   64
1  64  154

In [34]:
def naive_vector_dot(x, y):
    assert len(x.shape) == 1
    assert len(y.shape) == 1
    assert x.shape[0] == y.shape[0]
    
    z = 0.
    for i in range(x.shape[0]):
        z += x[i] * y[i]
    return z

In [35]:
def naive_matrix_vector_dot(x, y):
    assert len(x.shape) == 2
    assert len(y.shape) == 1
    assert x.shape[1] == y.shape[0]
    
    z = np.zeros(x.shape[0])
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            z[i] += x[i, j] * y[j]
    return z

In [36]:
def naive_matrix_vector_dot(x, y):
    z = np.zeros(x.shape[0])
    for i in range(x.shape[0]):
        z[i] = naive_vector_dot(x[i, :], y)
    return z

In [37]:
def naive_matrix_dot(x, y):
    assert len(x.shape) == 2
    assert len(y.shape) == 2
    assert x.shape[1] == y.shape[0]
    
    z = np.zeros((x.shape[0], y.shape[1]))
    for i in range(x.shape[0]):
        for j in range(y.shape[1]):
            row_x = x[i, :]
            column_y = y[:, j]
            z[i, j] = naive_vector_dot(row_x, column_y)
    return z

### Tensor reshaping

#### train_images = train_images.reshape((60000, 28 * 28))

In [35]:
x = np.array([[0., 1.],
              [2., 3.],
              [4., 5.]])
x.shape

(3, 2)

In [39]:
x = x.reshape((6,))
x

array([0., 1., 2., 3., 4., 5.])

In [40]:
x = x.reshape((2, 3))
x

array([[0., 1., 2.],
       [3., 4., 5.]])

In [41]:
x = np.zeros((300, 20))
x = np.transpose(x)
x.shape

(20, 300)

### Geometric interpretation of tensor operations

### A geometric interpretation of deep learning